fullnameOverride: kube-prometheus-stack
namespaceOverride: monitoring

prometheus:
  serviceAccount:
    create: true
  prometheusSpec:
    retention: 15d
    scrapeInterval: 30s
    evaluationInterval: 30s
    replicas: 1
    enableAdminAPI: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: "nfs-client"

alertmanager:
  alertmanagerSpec:
    replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - alertmanager.abdalrahman.tech
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.abdalrahman.tech
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: "nfs-client"

grafana:
  defaultDashboardsEnabled: true
  admin:
    user: admin
    password: "admin"
    existingSecret: ""
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - grafana.abdalrahman.tech
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.abdalrahman.tech
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "nfs-client"

kubeControllerManager:
  enabled: true
  service:
    enabled: true
    port: 10257
    targetPort: 10257
  serviceMonitor:
    enabled: true
    https: true
    insecureSkipVerify: true
    serverName: kubernetes
    endpoints:
      - 192.168.12.237

kubeScheduler:
  enabled: true
  service:
    enabled: true
    port: 10259
    targetPort: 10259
  serviceMonitor:
    enabled: true
    https: true
    insecureSkipVerify: true
    serverName: kubernetes
    endpoints:
      - 192.168.12.237

kubeProxy:
  enabled: true
  service:
    enabled: true
    port: 10249
    targetPort: 10249
  serviceMonitor:
    enabled: true

kubeEtcd:
  enabled: false

kube-state-metrics:
  prometheus:
    monitor:
      enabled: true

prometheus-node-exporter:
  hostRootfs: true