apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: passbolt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://download.passbolt.com/charts/passbolt
    chart: passbolt
    targetRevision: "1.4.0"
    helm:
      values: |
        fullnameOverride: passbolt

        redisDependencyEnabled: true
        mariadbDependencyEnabled: false
        postgresqlDependencyEnabled: true

        app:
          image:
            tag: 5.4.1-1-ce-non-root
          containerPorts:
            http: 8080
            https: 4433
          service:
            ports:
              http:
                port: 80 
                targetPort: 8080
              https:
                port: 443
                targetPort: 4433
          database:
            kind: postgresql

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - host: passbolt.abdalrahman.tech
              paths:
                - path: /
                  pathType: Prefix
                  port: 80

        persistence:
          enabled: true
          storageClass: nfs-client
          accessModes: ["ReadWriteOnce"]
          size: 10Gi

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        postgresql:
          global:
            security:
              allowInsecureImages: true
          image:
            registry: docker.io
            repository: bitnamilegacy/postgresql
            tag: "17"
          auth:
            username: passbolt
            password: "securepassword"
            database: passbolt
          primary:
            persistence:
              enabled: true
              storageClass: nfs-client
              size: 10Gi
          metrics:
            enabled: false

        redis:
          auth:
            enabled: true
            password: "changeme-redis"
          sentinel:
            enabled: true
          metrics:
            enabled: false

        passboltEnv:
          plain:
            APP_FULL_BASE_URL: "https://passbolt.abdalrahman.tech"
            CACHE_CAKE_DEFAULT_SERVER: "passbolt-redis"
            CACHE_CAKE_DEFAULT_PORT: "6379"
          secret:
            CACHE_CAKE_DEFAULT_PASSWORD: "changeme-redis"

        smtp:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: passbolt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
