apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: passbolt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://download.passbolt.com/charts/passbolt
    chart: passbolt
    targetRevision: "1.4.0"
    helm:
      values: |
        fullnameOverride: passbolt

        redisDependencyEnabled: true
        mariadbDependencyEnabled: false
        postgresqlDependencyEnabled: true

        app:
          database:
            kind: postgresql

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: passbolt.abdalrahman.tech
              paths:
                - path: /
                  pathType: Prefix
                  port: http

        persistence:
          enabled: true
          storageClass: nfs-client
          accessModes: ["ReadWriteOnce"]
          size: 10Gi

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        postgresql:
          auth:
            username: passbolt
            password: "securepassword"
            database: passbolt
          primary:
            persistence:
              enabled: true
              storageClass: nfs-client
              size: 10Gi
          metrics:
            enabled: false

        redis:
          auth:
            enabled: true
            password: "changeme-redis"
          sentinel:
            enabled: true
          metrics:
            enabled: false

        passboltEnv:
          plain:
            APP_FULL_BASE_URL: "https://passbolt.abdalrahman.tech"

        smtp:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: passbolt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
